(async () => {
  const C = DHD, S = DHDStorage, results = [];
  const assert = (value, message = 'assertion failed') => { if (!value) throw Error(message); };
  const rejects = async fn => { let rejected = false; try { await fn(); } catch (_) { rejected = true; } assert(rejected, 'Expected rejection'); };
  async function test(name, fn) { try { await fn(); results.push({ name, pass: true }); } catch (e) { results.push({ name, pass: false, error: e.message }); } const li = document.createElement('li'); const r = results.at(-1); li.textContent = `${r.pass ? 'PASS' : 'FAIL'} ${name}${r.error ? ': ' + r.error : ''}`; li.className = r.pass ? 'pass' : 'fail'; document.querySelector('#results').append(li); }
  const fixture = { schemaVersion: 1, id: 'TASK-TEST', title: '샘플', category: 'personal', status: 'planned', progress: 0, startDate: '2026-09-10', targetEndDate: null, actualEndDate: null, milestones: [], logs: [], decisions: [], releases: [], future: { keep: true } };
  const makeFiles = tasks => new Map([['index.json', C.bytes(C.json({ schemaVersion: 1, extra: 'preserved', tasks: tasks.map(t => ({ id: t.id, file: `tasks/${t.id}.json`, futureEntry: true })) }))], ...tasks.map(t => [`tasks/${t.id}.json`, C.bytes(C.json(t))])]);
  const workspace = async tasks => { const files = makeFiles(tasks); return new S.Workspace().load(async p => files.get(p), 'sample'); };
  await test('윤년·월 경계·종료일 계산', () => { assert(C.day('2024-02-29') + 1 === C.day('2024-03-01')); assert(C.day('2026-02-29') === null); assert(C.day('2026-12-31') + 1 === C.day('2027-01-01')); assert(C.endDate({...fixture, actualEndDate:'2026-09-15'}) === null); });
  await test('알 수 없는 필드와 index metadata 보존 / 재로딩', async () => { const ws = await workspace([fixture]); ws.record(fixture.id, {title:'변경'}); const copy = await new S.Workspace().load(async p => ws.files.get(p),'sample'); assert(copy.tasks[0].future.keep && copy.index.extra === 'preserved' && copy.index.tasks[0].futureEntry); assert(copy.tasks[0].title === '변경'); });
  await test('계층 재배치와 순환 방지', async () => { const ws = await workspace([fixture, {...fixture,id:'TASK-CHILD',parentId:fixture.id,progress:40}, {...fixture,id:'TASK-ROOT',progress:100}]); assert(C.progress(ws.tasks,ws.tasks[0]) === 40); await rejects(() => ws.relocate(fixture.id,'TASK-CHILD')); ws.relocate('TASK-CHILD','TASK-ROOT'); assert(ws.tasks[1].parentId === 'TASK-ROOT'); });
  await test('손상 파일 격리 및 저장 차단', async () => { const files=makeFiles([fixture,{...fixture,id:'TASK-BAD',progress:200}]); const ws=await new S.Workspace().load(async p=>files.get(p),'sample'); assert(ws.tasks.length===1 && ws.errors.length===1); await rejects(()=>ws.record(fixture.id,{title:'unsafe'})); });
  await test('Markdown 관리 영역 / 외부 영역 보존', () => { const md=C.writeBody('','text','- [ ] 확인')+'\n## 외부 추가\n보존\n'; const updated=C.writeBody(md,'바뀐 내용','- [x] 확인'); assert(updated.includes('## 외부 추가\n보존')); assert(C.parseBody(updated).description === '바뀐 내용'); });
  await test('ZIP 헤더·경로·본문·CRC 검증', async () => { const value=C.bytes('한글 테스트'); const zip=new Uint8Array(await C.zip(new Map([['web/data/notes/TASK-TEST.md',value]])).arrayBuffer()); const v=new DataView(zip.buffer); assert(v.getUint32(0,true)===0x04034b50); assert(v.getUint32(14,true)===C.crc32(value)); const n=v.getUint16(26,true); assert(C.text(zip.slice(30,30+n))==='web/data/notes/TASK-TEST.md'); assert(C.equal(zip.slice(30+n,30+n+value.length),value)); assert(v.getUint32(zip.length-22,true)===0x06054b50); assert(C.crc32(C.bytes('123456789'))===0xcbf43926); });
  await test('이미지 저장 및 SVG 차단', async () => { const ws=await workspace([fixture]); const png=Uint8Array.from(atob('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAusB9Wl2ZQAAAABJRU5ErkJggg=='),c=>c.charCodeAt(0)); const img=await ws.image(fixture,new File([png],'sample.png',{type:'image/png'})); assert(img.file.startsWith('images/TASK-TEST/')); await rejects(()=>ws.image(fixture,new File(['<svg/>'],'bad.svg'))); });
  await test('로컬 폴더 저장·외부 변경·권한 거부 (API 모형)', async () => {
    const ws=await workspace([fixture]); const disk=new Map(ws.files); let deny=false;
    function directory(prefix='') { return {async getDirectoryHandle(name){return directory(prefix+name+'/');},async getFileHandle(name,{create=false}={}){const p=prefix+name;if(!disk.has(p)&&!create)throw new DOMException('missing','NotFoundError');return {async getFile(){return new Blob([disk.get(p)]);},async createWritable(){if(deny)throw new DOMException('denied','NotAllowedError');let value;return {async write(v){value=v;},async close(){disk.set(p,value);},async abort(){}};}};}};}
    ws.directory=directory();ws.record(fixture.id,{title:'local edit'});await S.saveDirectory(ws);assert(!ws.changed().size);assert(JSON.parse(C.text(disk.get('tasks/TASK-TEST.json'))).title==='local edit');
    ws.record(fixture.id,{title:'next edit'});disk.set('tasks/TASK-TEST.json',C.bytes('external'));await rejects(()=>S.saveDirectory(ws));assert(ws.changed().size>0);disk.set('tasks/TASK-TEST.json',ws.baseline.get('tasks/TASK-TEST.json'));deny=true;await rejects(()=>S.saveDirectory(ws));assert(ws.changed().size>0);
  });
  const template=await (await fetch('../web/app.template.html')).text();
  const sources=Object.fromEntries(await Promise.all(['core','storage','app'].map(async name=>[name,await (await fetch(`../web/assets/${name}.js`)).text()])));
  const css=await(await fetch('../web/assets/styles.css')).text();
  async function appFrame(count) {
    const tasks=Array.from({length:count},(_,i)=>({...fixture,id:'TASK-PERF-'+i,title:i===0?'Root':`하위 작업 ${i}`,parentId:i? 'TASK-PERF-0':null,order:i,progress:i%101}));
    const files=Object.fromEntries([...makeFiles(tasks)].map(([p,b])=>[p,C.text(b)]));
    let html=template.replace('/*__STYLES__*/',css).replace('/*__BOOTSTRAP__*/','{}').replace('/*__CONFIG__*/',JSON.stringify({dataBase:'./data/'}));
    const setup=`window.__files=${JSON.stringify(files).replace(/</g,'\\u003c')};window.confirm=()=>true;window.fetch=async url=>{const p=new URL(url).pathname.split('/data/')[1];return new Response(window.__files[p]||'',{status:p in window.__files?200:404});};window.__blobs=[];const create=URL.createObjectURL.bind(URL);URL.createObjectURL=b=>{window.__blobs.push(b);return create(b);};`;
    html=html.replace('/*__CORE__*/',()=>setup+sources.core).replace('/*__STORAGE__*/',()=>sources.storage).replace('/*__APP__*/',()=>sources.app);
    const frame=document.createElement('iframe');frame.srcdoc=html;document.querySelector('#frames').append(frame);
    const started=performance.now();
    await new Promise((resolve,reject)=>{const timer=setInterval(()=>{if(frame.contentWindow.DHD_DIAGNOSTICS){clearInterval(timer);resolve();}else if(performance.now()-started>20000){clearInterval(timer);reject(Error('render timeout'));}},25);});
    return {frame,elapsed:performance.now()-started,doc:frame.contentDocument,win:frame.contentWindow};
  }
  let app;
  await test('300개 과제 실제 목록·간트 DOM 렌더링',async()=>{app=await appFrame(300);assert(app.doc.querySelectorAll('.task-row[data-id]').length===300);assert(app.win.DHD_DIAGNOSTICS().errorCount===0);assert(app.elapsed<10000,'render >10s');document.querySelector('#status').textContent=`300 tasks: ${Math.round(app.elapsed)}ms`;app.frame.remove();});
  await test('500개 과제 실제 목록·간트 DOM 렌더링',async()=>{app=await appFrame(500);assert(app.doc.querySelectorAll('.task-row[data-id]').length===500);assert(app.elapsed<10000,'render >10s');});
  await test('실제 폼 수정·미리보기·신규 하위 작업·XSS 안전성',async()=>{
    const d=app.doc;d.querySelector('.task-open').click();const title=d.querySelector('[name=title]');title.value='<img src=x onerror=alert(1)>';title.dispatchEvent(new Event('input',{bubbles:true}));d.querySelector('#applyTask').click();assert(app.win.DHD_DIAGNOSTICS().changedFiles>=2);assert(!d.querySelector('#tree img'));d.querySelector('[data-tab=body]').click();const description=d.querySelector('[name=description]');description.value='일반 폼 본문';description.dispatchEvent(new Event('input',{bubbles:true}));d.querySelector('.body-toolbar button').click();assert(d.querySelector('.preview').textContent.includes('일반 폼 본문'));d.querySelector('#applyTask').click();d.querySelector('#addChild').click();assert(app.win.DHD_DIAGNOSTICS().taskCount===501);d.querySelector('#closeTask').click();
  });
  await test('개발 로그·결정·마일스톤·릴리즈 폼 추가',async()=>{const d=app.doc;d.querySelector('#tree .task-open').click();for(const tab of ['logs','decisions','milestones','releases']){d.querySelector(`[data-tab=${tab}]`).click();d.querySelector('.collection-head button').click();assert(d.querySelectorAll('.record').length===1);d.querySelector('#applyTask').click();assert(!d.querySelector('#taskError').textContent);}d.querySelector('[data-tab=history]').click();assert(d.querySelectorAll('.history-item').length>=4);d.querySelector('#closeTask').click();});
  await test('상위 과제 보관·하위 작업 숨김·보관함 복구',async()=>{const d=app.doc;d.querySelector('#tree .task-open').click();d.querySelector('#archiveTask').click();d.querySelector('#applyTask').click();d.querySelector('#closeTask').click();assert(d.querySelectorAll('.task-row[data-id]').length===0);const toggle=d.querySelector('#showArchived');toggle.checked=true;toggle.dispatchEvent(new Event('change',{bubbles:true}));assert(d.querySelectorAll('.task-row[data-id]').length===501);d.querySelector('#tree .task-open').click();d.querySelector('#archiveTask').click();d.querySelector('#applyTask').click();d.querySelector('#closeTask').click();});
  await test('실제 드래그 이벤트 재배치와 순환 차단',async()=>{const d=app.doc;const target=d.querySelector('[data-id=TASK-PERF-1]');const transfer=new DataTransfer();transfer.setData('text/plain','TASK-PERF-2');const bounds=target.getBoundingClientRect();target.dispatchEvent(new DragEvent('dragover',{bubbles:true,cancelable:true,clientY:bounds.top+bounds.height/2,dataTransfer:transfer}));target.dispatchEvent(new DragEvent('drop',{bubbles:true,cancelable:true,dataTransfer:transfer}));d.querySelector('[data-id=TASK-PERF-2] .task-open').click();assert(d.querySelector('[name=parentId]').value==='TASK-PERF-1');d.querySelector('#closeTask').click();});
  await test('반응형 레이아웃 390/768/1024/1280',async()=>{for(const width of [390,768,1024,1280]){app.frame.style.width=width+'px';await new Promise(r=>requestAnimationFrame(()=>requestAnimationFrame(r)));assert(app.doc.documentElement.scrollWidth<=width+1,`page overflow at ${width}: ${app.doc.documentElement.scrollWidth}`);}});
  const failed=results.filter(r=>!r.pass);document.querySelector('#status').textContent=`${results.length-failed.length}/${results.length} passed · 500 rows ${app?Math.round(app.elapsed):'?'}ms`;document.body.dataset.result=failed.length?'fail':'pass';window.TEST_RESULTS=results;
})();
