(async () => {
  const C = DHD, S = DHDStorage, results = [];
  const assert = (value, message = 'assertion failed') => { if (!value) throw Error(message); };
  const rejects = async fn => { let rejected = false; try { await fn(); } catch (_) { rejected = true; } assert(rejected, 'Expected rejection'); };
  async function test(name, fn) { try { await fn(); results.push({ name, pass: true }); } catch (e) { results.push({ name, pass: false, error: e.message }); } const li = document.createElement('li'); const r = results.at(-1); li.textContent = `${r.pass ? 'PASS' : 'FAIL'} ${name}${r.error ? ': ' + r.error : ''}`; li.className = r.pass ? 'pass' : 'fail'; document.querySelector('#results').append(li); }
  const fixture = { schemaVersion: 1, id: 'TASK-TEST', title: '샘플', category: 'personal', status: 'planned', progress: 0, startDate: '2026-09-10', targetEndDate: null, actualEndDate: null, milestones: [], logs: [], decisions: [], releases: [], future: { keep: true } };
  const makeFiles = tasks => new Map([['index.json', C.bytes(C.json({ schemaVersion: 1, extra: 'preserved', tasks: tasks.map(t => ({ id: t.id, file: `tasks/${t.id}.json`, futureEntry: true })) }))], ...tasks.map(t => [`tasks/${t.id}.json`, C.bytes(C.json(t))])]);
  const workspace = async tasks => { const files = makeFiles(tasks); return new S.Workspace().load(async p => files.get(p), 'sample'); };
  await test('윤년·월 경계·종료일 계산', () => { assert(C.day('2024-02-29') + 1 === C.day('2024-03-01')); assert(C.day('2026-02-29') === null); assert(C.day('2026-12-31') + 1 === C.day('2027-01-01')); assert(C.endDate({...fixture, actualEndDate:'2026-09-15'}) === null); });
  await test('간트 날짜 이동은 일정만 같은 일수로 이동', () => { const shifted=C.shiftSchedule({...fixture,targetEndDate:'2026-09-20',actualEndDate:'2026-09-18',milestones:[{date:'2026-09-15'}]},5);assert(shifted.startDate==='2026-09-15'&&shifted.targetEndDate==='2026-09-25'&&shifted.actualEndDate==='2026-09-23');assert(shifted.milestones[0].date==='2026-09-15'); });
  await test('알 수 없는 필드와 index metadata 보존 / 재로딩', async () => { const ws = await workspace([fixture]); ws.record(fixture.id, {title:'변경'}); const copy = await new S.Workspace().load(async p => ws.files.get(p),'sample'); assert(copy.tasks[0].future.keep && copy.index.extra === 'preserved' && copy.index.tasks[0].futureEntry); assert(copy.tasks[0].title === '변경'); });
  await test('계층 재배치와 순환 방지', async () => { const ws = await workspace([fixture, {...fixture,id:'TASK-CHILD',parentId:fixture.id,progress:40}, {...fixture,id:'TASK-ROOT',progress:100}]); assert(C.progress(ws.tasks,ws.tasks[0]) === 40); await rejects(() => ws.relocate(fixture.id,'TASK-CHILD')); ws.relocate('TASK-CHILD','TASK-ROOT'); assert(ws.tasks[1].parentId === 'TASK-ROOT'); });
  await test('삭제는 하위 작업을 목록에서 제거하고 기존 파일 보존', async () => { const ws=await workspace([fixture,{...fixture,id:'TASK-CHILD',parentId:fixture.id}]);const removed=ws.remove(fixture.id);assert(removed.length===2&&ws.tasks.length===0);assert(ws.files.has('tasks/TASK-TEST.json')&&ws.files.has('tasks/TASK-CHILD.json'));assert(JSON.parse(C.text(ws.files.get('index.json'))).tasks.length===0);assert(ws.changed().size===1&&ws.changed().has('index.json')); });
  await test('손상 파일 격리 및 저장 차단', async () => { const files=makeFiles([fixture,{...fixture,id:'TASK-BAD',progress:200}]); const ws=await new S.Workspace().load(async p=>files.get(p),'sample'); assert(ws.tasks.length===1 && ws.errors.length===1); await rejects(()=>ws.record(fixture.id,{title:'unsafe'})); });
  await test('Undo/Redo 본문·일괄삭제·저장 후 복구·새 편집 분기', async () => {
    const ws=await workspace([fixture,{...fixture,id:'TASK-CHILD',parentId:fixture.id}]);
    ws.record(fixture.id,{title:'수정'},{description:'본문',checklist:''}); ws.saved();
    assert(ws.undo() && ws.tasks[0].title===fixture.title && ws.changed().size>0);
    assert(ws.redo() && ws.body(ws.tasks[0]).includes('본문'));
    const before=ws.undoStack.length; ws.removeMany([fixture.id,'TASK-CHILD']);
    assert(ws.tasks.length===0 && ws.undoStack.length===before+1); ws.saved();
    ws.undo(); assert(ws.tasks.length===2 && ws.changed().has('index.json'));
    ws.record(fixture.id,{title:'새 분기'}); assert(!ws.redo());
    const added=ws.add(); ws.saved(); ws.undo(); assert(!ws.tasks.some(t=>t.id===added.id));
    ws.redo(); assert(ws.tasks.some(t=>t.id===added.id));
  });
  await test('Markdown 관리 영역 / 외부 영역 보존', () => { const md=C.writeBody('','text','- [ ] 확인')+'\n## 외부 추가\n보존\n'; const updated=C.writeBody(md,'바뀐 내용','- [x] 확인'); assert(updated.includes('## 외부 추가\n보존')); assert(C.parseBody(updated).description === '바뀐 내용'); });
  await test('ZIP 헤더·경로·본문·CRC 검증', async () => { const value=C.bytes('한글 테스트'); const zip=new Uint8Array(await C.zip(new Map([['web/data/notes/TASK-TEST.md',value]])).arrayBuffer()); const v=new DataView(zip.buffer); assert(v.getUint32(0,true)===0x04034b50); assert(v.getUint32(14,true)===C.crc32(value)); const n=v.getUint16(26,true); assert(C.text(zip.slice(30,30+n))==='web/data/notes/TASK-TEST.md'); assert(C.equal(zip.slice(30+n,30+n+value.length),value)); assert(v.getUint32(zip.length-22,true)===0x06054b50); assert(C.crc32(C.bytes('123456789'))===0xcbf43926); });
  await test('이미지 저장 및 SVG 차단', async () => { const ws=await workspace([fixture]); const png=Uint8Array.from(atob('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAusB9Wl2ZQAAAABJRU5ErkJggg=='),c=>c.charCodeAt(0)); const img=await ws.image(fixture,new File([png],'sample.png',{type:'image/png'})); assert(img.file.startsWith('images/TASK-TEST/')); await rejects(()=>ws.image(fixture,new File(['<svg/>'],'bad.svg'))); });
  await test('로컬 폴더 저장·외부 변경·권한 거부 (API 모형)', async () => {
    const ws=await workspace([fixture]); const disk=new Map(ws.files); let deny=false;
    function directory(prefix='') { return {async getDirectoryHandle(name){return directory(prefix+name+'/');},async getFileHandle(name,{create=false}={}){const p=prefix+name;if(!disk.has(p)&&!create)throw new DOMException('missing','NotFoundError');return {async getFile(){return new Blob([disk.get(p)]);},async createWritable(){if(deny)throw new DOMException('denied','NotAllowedError');let value;return {async write(v){value=v;},async close(){disk.set(p,value);},async abort(){}};}};}};}
    ws.directory=directory();ws.record(fixture.id,{title:'local edit'});await S.saveDirectory(ws);assert(!ws.changed().size);assert(JSON.parse(C.text(disk.get('tasks/TASK-TEST.json'))).title==='local edit');
    ws.record(fixture.id,{title:'next edit'});disk.set('tasks/TASK-TEST.json',C.bytes('external'));await rejects(()=>S.saveDirectory(ws));assert(ws.changed().size>0);disk.set('tasks/TASK-TEST.json',ws.baseline.get('tasks/TASK-TEST.json'));deny=true;await rejects(()=>S.saveDirectory(ws));assert(ws.changed().size>0);
  });
  const template=await (await fetch('../web/app.template.html')).text();
  const sources=Object.fromEntries(await Promise.all(['core','storage','app'].map(async name=>[name,await (await fetch(`../web/assets/${name}.js`)).text()])));
  const css=await(await fetch('../web/assets/styles.css')).text();
  async function appFrame(count) {
    const tasks=Array.from({length:count},(_,i)=>({...fixture,id:'TASK-PERF-'+i,title:i===0?'Root':`하위 작업 ${i}`,parentId:i? 'TASK-PERF-0':null,order:i,progress:i%101,targetEndDate:'2026-10-10'}));
    const files=Object.fromEntries([...makeFiles(tasks)].map(([p,b])=>[p,C.text(b)]));
    let html=template.replace('/*__STYLES__*/',css).replace('/*__BOOTSTRAP__*/','{}').replace('/*__CONFIG__*/',JSON.stringify({dataBase:'./data/'}));
    const setup=`window.__files=${JSON.stringify(files).replace(/</g,'\\u003c')};window.confirm=()=>true;window.fetch=async url=>{const p=new URL(url).pathname.split('/data/')[1];return new Response(window.__files[p]||'',{status:p in window.__files?200:404});};window.__blobs=[];const create=URL.createObjectURL.bind(URL);URL.createObjectURL=b=>{window.__blobs.push(b);return create(b);};`;
    html=html.replace('/*__CORE__*/',()=>setup+sources.core).replace('/*__STORAGE__*/',()=>sources.storage).replace('/*__APP__*/',()=>sources.app);
    const frame=document.createElement('iframe');frame.srcdoc=html;document.querySelector('#frames').append(frame);
    const started=performance.now();
    await new Promise((resolve,reject)=>{const timer=setInterval(()=>{if(frame.contentWindow.DHD_DIAGNOSTICS){clearInterval(timer);resolve();}else if(performance.now()-started>20000){clearInterval(timer);reject(Error('render timeout'));}},25);});
    return {frame,elapsed:performance.now()-started,doc:frame.contentDocument,win:frame.contentWindow};
  }
  let app;
  await test('300개 과제 실제 목록·간트 DOM 렌더링',async()=>{app=await appFrame(300);assert(app.doc.querySelectorAll('.task-row[data-id]').length===300);assert(app.win.DHD_DIAGNOSTICS().errorCount===0);assert(app.elapsed<10000,'render >10s');document.querySelector('#status').textContent=`300 tasks: ${Math.round(app.elapsed)}ms`;app.frame.remove();});
  await test('500개 과제 실제 목록·간트 DOM 렌더링',async()=>{app=await appFrame(500);assert(app.doc.querySelectorAll('.task-row[data-id]').length===500);assert(app.elapsed<10000,'render >10s');});
  await test('실제 폼 수정·미리보기·신규 하위 작업·XSS 안전성',async()=>{
    const d=app.doc;d.querySelector('.task-open').click();const title=d.querySelector('[name=title]');title.value='<img src=x onerror=alert(1)>';title.dispatchEvent(new Event('input',{bubbles:true}));d.querySelector('#applyTask').click();assert(app.win.DHD_DIAGNOSTICS().changedFiles>=2);assert(!d.querySelector('#tree img'));d.querySelector('[data-tab=body]').click();const description=d.querySelector('[name=description]');description.value='일반 폼 본문';description.dispatchEvent(new Event('input',{bubbles:true}));d.querySelector('.body-toolbar button').click();assert(d.querySelector('.preview').textContent.includes('일반 폼 본문'));d.querySelector('#applyTask').click();d.querySelector('#addChild').click();assert(app.win.DHD_DIAGNOSTICS().taskCount===501);d.querySelector('#closeTask').click();
  });
  await test('개발 로그·결정·마일스톤·릴리즈 폼 추가',async()=>{const d=app.doc;d.querySelector('#tree .task-open').click();for(const tab of ['logs','decisions','milestones','releases']){d.querySelector(`[data-tab=${tab}]`).click();d.querySelector('.collection-head button').click();assert(d.querySelectorAll('.record').length===1);d.querySelector('#applyTask').click();assert(!d.querySelector('#taskError').textContent);}d.querySelector('[data-tab=history]').click();assert(d.querySelectorAll('.history-item').length>=4);d.querySelector('#closeTask').click();});
  await test('보관된 과제만 별도 조회·복구',async()=>{const d=app.doc;d.querySelector('#tree .task-open').click();d.querySelector('#archiveTask').click();d.querySelector('#applyTask').click();d.querySelector('#closeTask').click();assert(d.querySelectorAll('.task-row[data-id]').length===0);const filter=d.querySelector('#archiveMode');filter.value='archived';filter.dispatchEvent(new Event('change',{bubbles:true}));assert(d.querySelectorAll('.task-row[data-id]').length===501);d.querySelector('#tree .task-open').click();d.querySelector('#archiveTask').click();d.querySelector('#applyTask').click();d.querySelector('#closeTask').click();assert(d.querySelectorAll('.task-row[data-id]').length===0);filter.value='active';filter.dispatchEvent(new Event('change',{bubbles:true}));assert(d.querySelectorAll('.task-row[data-id]').length===501);});
  await test('실제 드래그 이벤트 재배치와 순환 차단',async()=>{const d=app.doc;const target=d.querySelector('[data-id=TASK-PERF-1]');const transfer=new DataTransfer();transfer.setData('text/plain','TASK-PERF-2');const bounds=target.getBoundingClientRect();target.dispatchEvent(new DragEvent('dragover',{bubbles:true,cancelable:true,clientY:bounds.top+bounds.height/2,dataTransfer:transfer}));target.dispatchEvent(new DragEvent('drop',{bubbles:true,cancelable:true,dataTransfer:transfer}));d.querySelector('[data-id=TASK-PERF-2] .task-open').click();assert(d.querySelector('[name=parentId]').value==='TASK-PERF-1');d.querySelector('#closeTask').click();});
  await test('완료 상태의 실제 종료일을 비워서 저장',async()=>{const d=app.doc;d.querySelector('#tree [data-id=TASK-PERF-3] .task-open').click();const status=d.querySelector('[name=status]');status.value='completed';status.dispatchEvent(new Event('input',{bubbles:true}));let actual=d.querySelector('[name=actualEndDate]');actual.value='2026-10-05';actual.dispatchEvent(new Event('input',{bubbles:true}));d.querySelector('#applyTask').click();actual=d.querySelector('[name=actualEndDate]');actual.value='';actual.dispatchEvent(new Event('input',{bubbles:true}));d.querySelector('#applyTask').click();d.querySelector('#closeTask').click();d.querySelector('#tree [data-id=TASK-PERF-3] .task-open').click();assert(d.querySelector('[name=actualEndDate]').value==='');d.querySelector('#closeTask').click();});
  await test('목록에서 완료 변경해도 실제 종료일 자동 입력 안 함',async()=>{const d=app.doc,row=d.querySelector('#tree [data-id=TASK-PERF-7]'),status=row.querySelector('.row-status');status.value='completed';status.dispatchEvent(new Event('change',{bubbles:true}));d.querySelector('#tree [data-id=TASK-PERF-7] .task-open').click();assert(d.querySelector('[name=actualEndDate]').value==='');d.querySelector('#closeTask').click();});
  await test('간트 마우스 오버 최신 상태 요약',async()=>{const d=app.doc;d.querySelector('#ganttView').click();const bar=d.querySelector('[data-id=TASK-PERF-0] .gantt-bar'),tip=d.querySelector('[data-id=TASK-PERF-0] .gantt-tooltip');bar.dispatchEvent(new PointerEvent('pointerenter',{bubbles:true,clientX:500}));assert(!tip.hidden&&tip.textContent.includes('최근')&&tip.textContent.includes('%'));bar.dispatchEvent(new PointerEvent('pointerleave',{bubbles:true}));assert(tip.hidden);});
  await test('간트 과제 위·아래 순서 이동',async()=>{const d=app.doc;const moving=d.querySelector('#gantt [data-id=TASK-PERF-3] .gantt-task-label .drag-handle'),target=d.querySelector('#gantt [data-id=TASK-PERF-5]');const transfer=new DataTransfer();moving.dispatchEvent(new DragEvent('dragstart',{bubbles:true,cancelable:true,dataTransfer:transfer}));const box=target.getBoundingClientRect();target.dispatchEvent(new DragEvent('dragover',{bubbles:true,cancelable:true,clientY:box.bottom-2,dataTransfer:transfer}));target.dispatchEvent(new DragEvent('drop',{bubbles:true,cancelable:true,clientY:box.bottom-2,dataTransfer:transfer}));const ids=[...d.querySelectorAll('#gantt .gantt-row[data-id]')].map(row=>row.dataset.id);assert(ids.indexOf('TASK-PERF-3')>ids.indexOf('TASK-PERF-5'));});
  await test('간트 터치 잠금·취소·확인·자동 재잠금',async()=>{
    const d=app.doc;
    const drag=()=>{const bar=d.querySelector('#gantt [data-id=TASK-PERF-4] .gantt-bar'); for(const [type,x] of [['pointerdown',500],['pointermove',560],['pointerup',560]])bar.dispatchEvent(new PointerEvent(type,{bubbles:true,cancelable:true,button:0,pointerType:'touch',pointerId:7,clientX:x}));};
    let confirmations=0; app.win.confirm=()=>{confirmations++;return false;};
    const dirty=app.win.DHD_DIAGNOSTICS().changedFiles; drag(); assert(confirmations===0&&dirty===app.win.DHD_DIAGNOSTICS().changedFiles);
    d.querySelector('#scheduleEditButton').click(); drag(); assert(confirmations===1&&d.querySelector('#scheduleEditButton').getAttribute('aria-pressed')==='false');
    d.querySelector('#tree [data-id=TASK-PERF-4] .task-open').click(); assert(d.querySelector('[name=startDate]').value==='2026-09-10'); d.querySelector('#closeTask').click();
    app.win.confirm=()=>true;d.querySelector('#scheduleEditButton').click();drag();
    d.querySelector('#treeView').click();d.querySelector('#tree [data-id=TASK-PERF-4] .task-open').click();assert(d.querySelector('[name=startDate]').value!=='2026-09-10');d.querySelector('#closeTask').click();
    d.querySelector('#undoButton').click();d.querySelector('#tree [data-id=TASK-PERF-4] .task-open').click();assert(d.querySelector('[name=startDate]').value==='2026-09-10');d.querySelector('#closeTask').click();d.querySelector('#redoButton').click();
  });
  await test('간트 접기·모두 접기/펼치기·목록 동기화',async()=>{const d=app.doc;d.querySelector('#ganttView').click();d.querySelector('#gantt [data-id=TASK-PERF-0] .fold').click();assert(d.querySelectorAll('#gantt [data-id]').length===1&&d.querySelectorAll('#tree [data-id]').length===1);d.querySelector('#expandButton').click();assert(d.querySelectorAll('#gantt [data-id]').length===501);d.querySelector('#collapseButton').click();assert(d.querySelectorAll('#gantt [data-id]').length===1);d.querySelector('#expandButton').click();d.querySelector('#treeView').click();});
  await test('일괄 선택 삭제 취소·하위 포함·Undo/Redo 한 단계',async()=>{const d=app.doc,before=app.win.DHD_DIAGNOSTICS().taskCount;d.querySelector('#bulkModeButton').click();d.querySelector('#tree [data-id=TASK-PERF-1] .task-check').click();d.querySelector('#tree [data-id=TASK-PERF-2] .task-check').click();app.win.confirm=()=>false;d.querySelector('#bulkDeleteButton').click();assert(app.win.DHD_DIAGNOSTICS().taskCount===before);app.win.confirm=()=>true;d.querySelector('#bulkDeleteButton').click();assert(app.win.DHD_DIAGNOSTICS().taskCount===before-2);d.querySelector('#undoButton').click();assert(app.win.DHD_DIAGNOSTICS().taskCount===before);d.querySelector('#redoButton').click();assert(app.win.DHD_DIAGNOSTICS().taskCount===before-2);d.querySelector('#undoButton').click();});
  await test('라이트·다크 테마 전환',async()=>{const d=app.doc,select=d.querySelector('#themeSelect');select.value='light';select.dispatchEvent(new Event('change',{bubbles:true}));assert(d.documentElement.dataset.theme==='light'&&app.win.getComputedStyle(d.body).backgroundColor==='rgb(244, 246, 251)');select.value='dark';select.dispatchEvent(new Event('change',{bubbles:true}));assert(d.documentElement.dataset.theme==='dark');});
  await test('과제 삭제 버튼은 하위 작업 포함 삭제',async()=>{const d=app.doc;const before=app.win.DHD_DIAGNOSTICS().taskCount;d.querySelector('[data-id=TASK-PERF-6] .task-open').click();d.querySelector('#deleteTask').click();assert(!d.querySelector('#taskDialog').open);assert(app.win.DHD_DIAGNOSTICS().taskCount===before-1);});
  await test('반응형 레이아웃 390/768/1024/1280',async()=>{for(const width of [390,768,1024,1280]){app.frame.style.width=width+'px';await new Promise(r=>requestAnimationFrame(()=>requestAnimationFrame(r)));assert(app.doc.documentElement.scrollWidth<=width+1,`page overflow at ${width}: ${app.doc.documentElement.scrollWidth}`);}});
  const failed=results.filter(r=>!r.pass);document.querySelector('#status').textContent=`${results.length-failed.length}/${results.length} passed · 500 rows ${app?Math.round(app.elapsed):'?'}ms`;document.body.dataset.result=failed.length?'fail':'pass';window.TEST_RESULTS=results;
})();
